#!/bin/sh
set -ex
ROOTDIR=$(cd $(dirname $0)/../ && pwd -P)

rm -rf MK_DIST

if [ ! -x ./script/build/unix/install ]; then
  git submodule update --init
fi

# install dependencies

./script/build/unix/install `./script/build/unix/all-deps.sh ios-`
./script/build/unix/install ios-measurement-kit

# make frameworks

./script/build/unix/framework-ios `./script/build/unix/all-deps.sh`
./script/build/unix/framework-ios measurement-kit
mv Framework Frameworks
