#!/bin/sh
set -e
ROOTDIR=$(cd $(dirname $0)/../ && pwd -P)

set -x
rm -rf MK_DIST

if [ ! -x ./pkgbuild/script/install/install ]; then
  git submodule update --init
fi

# x86_64

./pkgbuild/script/install/install testing/iphonesimulator-x86_64-geoip-1.6.12-2
./pkgbuild/script/install/install testing/iphonesimulator-x86_64-libevent-2.1.8-2
./pkgbuild/script/install/install testing/iphonesimulator-x86_64-libressl-2.6.4-2
./pkgbuild/script/install/install testing/iphonesimulator-x86_64-measurement_kit-0.9.0-alpha-2
./pkgbuild/script/install/install testing/iphonesimulator-x86_64-api-objective-c-f9a3bd31a39e90fa656e8e55e2e7632d2fb27606-1

# CombinedLibs

rm -rf CombinedLibs
install -d CombinedLibs

## x86_64

/usr/bin/libtool -static -o CombinedLibs/x86_64.a                              \
  MK_DIST/iphonesimulator/x86_64/geoip-1.6.12-2/lib/libGeoIP.a                 \
  MK_DIST/iphonesimulator/x86_64/libressl-2.6.4-2/lib/libcrypto.a              \
  MK_DIST/iphonesimulator/x86_64/libressl-2.6.4-2/lib/libssl.a                 \
  MK_DIST/iphonesimulator/x86_64/libevent-2.1.8-2/lib/libevent.a               \
  MK_DIST/iphonesimulator/x86_64/libevent-2.1.8-2/lib/libevent_pthreads.a      \
  MK_DIST/iphonesimulator/x86_64/libevent-2.1.8-2/lib/libevent_openssl.a       \
  MK_DIST/iphonesimulator/x86_64/measurement_kit-0.9.0-alpha-2/lib/libmeasurement_kit.a \
  MK_DIST/iphonesimulator/x86_64/api-objective-c-f9a3bd31a39e90fa656e8e55e2e7632d2fb27606-1/lib/libmeasurementkit-objectivec.a

# Frameworks
#
# Note: using the x86_64 headers because headers are MI.

rm -rf Frameworks
install -d Frameworks/MeasurementKit.framework
lipo -create -output Frameworks/MeasurementKit.framework/MeasurementKit        \
  CombinedLibs/x86_64.a
install -d Frameworks/MeasurementKit.framework/Headers/MeasurementKit
install -m644 MK_DIST/iphonesimulator/x86_64/api-objective-c-f9a3bd31a39e90fa656e8e55e2e7632d2fb27606-1/include/*.h \
  Frameworks/MeasurementKit.framework/Headers/MeasurementKit
